spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youtube2025
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: YouTube2025

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false              # show_sql через Hibernate — ВИМКНЕНО (ламає батчінг)
    open-in-view: false
    properties:
      hibernate:
        show_sql: false          # так само ВИМКНЕНО
        #generate_statistics: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
        web.servlet.DispatcherServlet: DEBUG
        web.client.RestTemplate: INFO
        web.HttpLogging: WARN
        boot.context.config: DEBUG
        data.repository.config.RepositoryConfigurationExtensionSupport: WARN
      hibernate:
        # SQL: DEBUG               # друкує всі SQL
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE # друкує значення параметрів
        #stat: DEBUG              # статистика батчів
#        engine:
#          jdbc:
#            batch:
#              internal: DEBUG   # реальні JDBC batch
#            spi:
#              SqlStatementLogger: TRACE


